### Basic GET request
GET https://api.thecatapi.com/v1/images/search

@BASE_URL = https://api.thecatapi.com/v1
@API_KEY = your_api_key_here

### GET request with variables and request parameters
GET {{BASE_URL}}/images/search?limit=3

### Request with environment variables
GET {{FROM_ENV_FILE_URL}}/breeds

### Named request
# @name SIAMESE_CATS
GET {{BASE_URL}}/breeds/search?q=siamese

### Usecase: Cookie
### Variables
@baseUrl = {{UD_URL_PREFIX}}/mahjong

### Login (required for authentication)
# @name login
POST {{UD_URL_PREFIX}}/auth/login
Content-Type: application/json

{
    "username": "admin@oatnil.com",
    "password": "admin123"
}

### Create new mahjong pattern
POST {{baseUrl}}
Content-Type: application/json
Cookie: access_token={{login.response.cookies.access_token.value}}

{
    "pai": "1w,2w",
    "description": "边搭，搭3万",
    "groupSuggestions": []
}

### Usecase: Access Token
### auth request
GET {{BASE_URL}}/images/search
Authorization: Bearer {{API_KEY}}

### POST request
POST {{BASE_URL}}/votes
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

{
    "image_id": "image_id_here",
    "value": 1
}

